### ISSUE TITLE
Branches won't show up in Figtree

### ISSUE THREAD

**Issue by johngphillips** [rambaut/figtree#135] opened 2019-02-24 16:14 UTC
I am attempting to use FigTree (1.4.4) to visualize a tree I created using BEAST2. For some reason I cannot figure out, no branches are showing up in my tree (screen shot attached). 

![screen shot 2019-02-24 at 8 13 02 am](https://user-images.githubusercontent.com/47947470/53301799-08358900-380c-11e9-8244-9c71ee13d5ab.png)

Taxon labels are visible and looking at the text, the parenthetical tree looks right to me.

Is this a common problem that anyone else has encountered/figured out? Treefile is attached.

Thank you,
-John

 

[Untitled.txt](https://github.com/rambaut/figtree/files/2898084/Untitled.txt)

**Comment by rambaut** [comment] 2019-02-24 18:07
The issue is that your branch lengths (and node heights etc.) are very very small (e.g., 3.34315999750482E-309). I think this is just being rounded to zero. It seems like there is an issue with your BEAST run.

I am going to close this issue.

**Closed by rambaut** 2019-02-24 18:07 UTC
